services:
  mysql_db:
    container_name: mysql_db
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./env/local.env
    tty: true
  redis_broker:
    image: "redis:alpine"
    container_name: redis_broker
    ports:
      - "6379:6379"
  celery_worker:
    build: ./python_api
    container_name: celery_worker
    command: celery -A worker.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis_broker
  # python_api:
  #   depends_on:
  #     - mysql_db
  #   container_name: python_api
  #   build: ./python_api
  #   restart: unless-stopped
  #   tty: true
  #   volumes:
  #     - ./python_api:/app
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - ./env/local.env
  fastapi:
    depends_on:
      - mysql_db
    container_name: fastapi
    build: ./fastapi
    restart: unless-stopped
    tty: true
    volumes:
      - ./fastapi:/app
    ports:
      - 8080:8080
    env_file:
      - ./env/local.env
  php_api:
    depends_on:
      - mysql_db
    container_name: php_api
    build: ./php_api
    restart: unless-stopped
    tty: true
    volumes:
      - /var/www/slim_app/vendor
      - ./php_api:/var/www/slim_app
    ports:
      - 8000:8000
    env_file:
      - ./env/local.env
  frontend:
    depends_on:
      - php_api
    container_name: next_frontend
    build: ./frontend
    restart: unless-stopped
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - ./env/local.env