version: '3.8'
services:
  mysql:
    container_name: mysql
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./env/local.env
    tty: true
  python_api:
    depends_on:
      - mysql
    container_name: python_api
    build: ./python_api
    restart: unless-stopped
    tty: true
    volumes:
      - ./python_api:/app
    ports:
      - 8080:8080
    env_file:
      - ./env/local.env
  php_api:
    depends_on:
      - mysql
    container_name: php_api
    build: ./php_api
    restart: unless-stopped
    tty: true
    volumes:
      - /var/www/slim_app/vendor
      - ./php_api:/var/www/slim_app
    ports:
      - 8000:8000
    environment:
      - JWT_SECRET=simple_jwt_key
  frontend:
    depends_on:
      - python_api
    container_name: next_frontend
    build: ./frontend
    restart: unless-stopped
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - ./env/local.env