"""Updated relationships

Revision ID: 5bdc7ff8265f
Revises: e5d4ac83048b
Create Date: 2024-10-25 16:20:27.846203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5bdc7ff8265f'
down_revision: Union[str, None] = 'e5d4ac83048b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_team_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('away_team_id', sa.Integer(), nullable=True))
    op.alter_column('game', 'stadium_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'game', 'stadium', ['stadium_id'], ['id'])
    op.create_foreign_key(None, 'game', 'team', ['away_team_id'], ['id'])
    op.create_foreign_key(None, 'game', 'team', ['home_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.alter_column('game', 'stadium_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('game', 'away_team_id')
    op.drop_column('game', 'home_team_id')
    # ### end Alembic commands ###
